### ISSUE TITLE
Parquet no longer exports RecCursor, but, you still refer to it.

### ISSUE THREAD

**Issue by blairn** [queryverse/ParquetFiles.jl#26]
Parquet.jl has updated, RecCursor isn't exported, so ParquetFile is broken. 

It should be updated to use RecordCursor, but currently is unusable.

Which of course, breaks Queryverse.

**Comment by xiaodaigh** [comment]
> Which of course, breaks Queryverse.

That's quite unfortunate indeed!

https://github.com/queryverse/ParquetFiles.jl/blob/d836c63396bad4675ba0bcad1290da33f26f789e/Project.toml#L25

But it's due to the unfortunate nature of the compat here which didn't set an upper bound. 

See https://github.com/queryverse/ParquetFiles.jl/pull/27 for a fix
